name: mukai
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.6.0
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.4
  iconify_flutter_plus: ^1.0.3
  intl_phone_field: ^3.2.0
  pinput: ^5.0.0
  animated_bottom_navigation_bar: ^1.3.3
  icons_plus: ^5.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.2.1
  google_maps_flutter: ^2.10.0
  supabase_flutter: ^2.9.0
  uuid: ^4.5.1
  firebase_core: ^3.3.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  dropdown_search: ^6.0.2
  multi_select_flutter: ^4.1.3
  timeago: ^3.7.0
  vibration: ^2.0.0
  nfc_manager: ^3.5.0
  flutter_cache_manager: ^3.4.1
  flutter_map: ^8.0.0
  flutter_map_cancellable_tile_provider: ^3.1.0
  shimmer: ^3.0.0
  isar: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  google_sign_in: ^6.3.0
  qr_flutter: ^4.1.0
  ndef: ^0.3.4
  flutter_nfc_kit: ^3.6.0
  mobile_scanner: ^6.0.10
  brick_offline_first_with_supabase: ^2.0.0
  brick_sqlite: ^4.0.2
  brick_supabase: ^2.0.0
  sqflite: ^2.4.1
  flutter_gen: ^5.10.0
  fl_chart: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  brick_offline_first_with_supabase_build: ^2.0.0
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
