// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250508174937_up = [
  InsertTable('_brick_Cooperative_members'),
  InsertTable('Cooperative'),
  InsertTable('Profile'),
  InsertTable('Transaction'),
  InsertTable('Wallet'),
  InsertForeignKey('_brick_Cooperative_members', 'Cooperative', foreignKeyColumn: 'l_Cooperative_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertForeignKey('_brick_Cooperative_members', 'Profile', foreignKeyColumn: 'f_Profile_brick_id', onDeleteCascade: true, onDeleteSetDefault: false),
  InsertColumn('id', Column.varchar, onTable: 'Cooperative', unique: true),
  InsertColumn('name', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('category', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('city', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('county', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('province_state', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('admin_id', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('members', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('password', Column.varchar, onTable: 'Profile'),
  InsertColumn('profile_image_url', Column.varchar, onTable: 'Profile'),
  InsertColumn('profile_image_id', Column.varchar, onTable: 'Profile'),
  InsertColumn('gender', Column.varchar, onTable: 'Profile'),
  InsertColumn('first_name', Column.varchar, onTable: 'Profile'),
  InsertColumn('last_name', Column.varchar, onTable: 'Profile'),
  InsertColumn('full_name', Column.varchar, onTable: 'Profile'),
  InsertColumn('profile_picture_id', Column.varchar, onTable: 'Profile'),
  InsertColumn('account_type', Column.varchar, onTable: 'Profile'),
  InsertColumn('email', Column.varchar, onTable: 'Profile'),
  InsertColumn('phone', Column.varchar, onTable: 'Profile'),
  InsertColumn('city', Column.varchar, onTable: 'Profile'),
  InsertColumn('country', Column.varchar, onTable: 'Profile'),
  InsertColumn('neighbourhood', Column.varchar, onTable: 'Profile'),
  InsertColumn('province_state', Column.varchar, onTable: 'Profile'),
  InsertColumn('id', Column.varchar, onTable: 'Profile'),
  InsertColumn('wallet_balance', Column.Double, onTable: 'Profile'),
  InsertColumn('wallet_address', Column.varchar, onTable: 'Profile'),
  InsertColumn('push_token', Column.varchar, onTable: 'Profile'),
  InsertColumn('business', Column.varchar, onTable: 'Profile'),
  InsertColumn('business_id', Column.varchar, onTable: 'Profile'),
  InsertColumn('business_name', Column.varchar, onTable: 'Profile'),
  InsertColumn('last_access', Column.datetime, onTable: 'Profile'),
  InsertColumn('created_at', Column.datetime, onTable: 'Profile'),
  InsertColumn('updated_at', Column.datetime, onTable: 'Profile'),
  InsertColumn('permissions', Column.varchar, onTable: 'Profile'),
  InsertColumn('category', Column.varchar, onTable: 'Transaction'),
  InsertColumn('purpose', Column.varchar, onTable: 'Transaction'),
  InsertColumn('id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('sending_wallet', Column.varchar, onTable: 'Transaction'),
  InsertColumn('account_id', Column.varchar, onTable: 'Transaction'),
  InsertColumn('sending_phone', Column.varchar, onTable: 'Transaction'),
  InsertColumn('receiving_wallet', Column.varchar, onTable: 'Transaction'),
  InsertColumn('receiving_phone', Column.varchar, onTable: 'Transaction'),
  InsertColumn('receiving_account_number', Column.varchar, onTable: 'Transaction'),
  InsertColumn('recieving_profile_avatar', Column.varchar, onTable: 'Transaction'),
  InsertColumn('sending_profile_avatar', Column.varchar, onTable: 'Transaction'),
  InsertColumn('status', Column.varchar, onTable: 'Transaction'),
  InsertColumn('transfer_mode', Column.varchar, onTable: 'Transaction'),
  InsertColumn('transfer_category', Column.varchar, onTable: 'Transaction'),
  InsertColumn('amount', Column.Double, onTable: 'Transaction'),
  InsertColumn('created_at', Column.varchar, onTable: 'Transaction'),
  InsertColumn('updated_at', Column.varchar, onTable: 'Transaction'),
  InsertColumn('category', Column.varchar, onTable: 'Wallet'),
  InsertColumn('purpose', Column.varchar, onTable: 'Wallet'),
  InsertColumn('id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('wallet_adress', Column.varchar, onTable: 'Wallet'),
  InsertColumn('account_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('phone_number', Column.varchar, onTable: 'Wallet'),
  InsertColumn('status', Column.varchar, onTable: 'Wallet'),
  InsertColumn('created_at', Column.varchar, onTable: 'Wallet'),
  InsertColumn('updated_at', Column.varchar, onTable: 'Wallet'),
  InsertColumn('recent_balance', Column.Double, onTable: 'Wallet'),
  CreateIndex(columns: ['l_Cooperative_brick_id', 'f_Profile_brick_id'], onTable: '_brick_Cooperative_members', unique: true)
];

const List<MigrationCommand> _migration_20250508174937_down = [
  DropTable('_brick_Cooperative_members'),
  DropTable('Cooperative'),
  DropTable('Profile'),
  DropTable('Transaction'),
  DropTable('Wallet'),
  DropColumn('l_Cooperative_brick_id', onTable: '_brick_Cooperative_members'),
  DropColumn('f_Profile_brick_id', onTable: '_brick_Cooperative_members'),
  DropColumn('id', onTable: 'Cooperative'),
  DropColumn('name', onTable: 'Cooperative'),
  DropColumn('category', onTable: 'Cooperative'),
  DropColumn('city', onTable: 'Cooperative'),
  DropColumn('county', onTable: 'Cooperative'),
  DropColumn('province_state', onTable: 'Cooperative'),
  DropColumn('admin_id', onTable: 'Cooperative'),
  DropColumn('members', onTable: 'Cooperative'),
  DropColumn('password', onTable: 'Profile'),
  DropColumn('profile_image_url', onTable: 'Profile'),
  DropColumn('profile_image_id', onTable: 'Profile'),
  DropColumn('gender', onTable: 'Profile'),
  DropColumn('first_name', onTable: 'Profile'),
  DropColumn('last_name', onTable: 'Profile'),
  DropColumn('full_name', onTable: 'Profile'),
  DropColumn('profile_picture_id', onTable: 'Profile'),
  DropColumn('account_type', onTable: 'Profile'),
  DropColumn('email', onTable: 'Profile'),
  DropColumn('phone', onTable: 'Profile'),
  DropColumn('city', onTable: 'Profile'),
  DropColumn('country', onTable: 'Profile'),
  DropColumn('neighbourhood', onTable: 'Profile'),
  DropColumn('province_state', onTable: 'Profile'),
  DropColumn('id', onTable: 'Profile'),
  DropColumn('wallet_balance', onTable: 'Profile'),
  DropColumn('wallet_address', onTable: 'Profile'),
  DropColumn('push_token', onTable: 'Profile'),
  DropColumn('business', onTable: 'Profile'),
  DropColumn('business_id', onTable: 'Profile'),
  DropColumn('business_name', onTable: 'Profile'),
  DropColumn('last_access', onTable: 'Profile'),
  DropColumn('created_at', onTable: 'Profile'),
  DropColumn('updated_at', onTable: 'Profile'),
  DropColumn('permissions', onTable: 'Profile'),
  DropColumn('category', onTable: 'Transaction'),
  DropColumn('purpose', onTable: 'Transaction'),
  DropColumn('id', onTable: 'Transaction'),
  DropColumn('sending_wallet', onTable: 'Transaction'),
  DropColumn('account_id', onTable: 'Transaction'),
  DropColumn('sending_phone', onTable: 'Transaction'),
  DropColumn('receiving_wallet', onTable: 'Transaction'),
  DropColumn('receiving_phone', onTable: 'Transaction'),
  DropColumn('receiving_account_number', onTable: 'Transaction'),
  DropColumn('recieving_profile_avatar', onTable: 'Transaction'),
  DropColumn('sending_profile_avatar', onTable: 'Transaction'),
  DropColumn('status', onTable: 'Transaction'),
  DropColumn('transfer_mode', onTable: 'Transaction'),
  DropColumn('transfer_category', onTable: 'Transaction'),
  DropColumn('amount', onTable: 'Transaction'),
  DropColumn('created_at', onTable: 'Transaction'),
  DropColumn('updated_at', onTable: 'Transaction'),
  DropColumn('category', onTable: 'Wallet'),
  DropColumn('purpose', onTable: 'Wallet'),
  DropColumn('id', onTable: 'Wallet'),
  DropColumn('wallet_adress', onTable: 'Wallet'),
  DropColumn('account_id', onTable: 'Wallet'),
  DropColumn('phone_number', onTable: 'Wallet'),
  DropColumn('status', onTable: 'Wallet'),
  DropColumn('created_at', onTable: 'Wallet'),
  DropColumn('updated_at', onTable: 'Wallet'),
  DropColumn('recent_balance', onTable: 'Wallet'),
  DropIndex('index__brick_Cooperative_members_on_l_Cooperative_brick_id_f_Profile_brick_id')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250508174937',
  up: _migration_20250508174937_up,
  down: _migration_20250508174937_down,
)
class Migration20250508174937 extends Migration {
  const Migration20250508174937()
    : super(
        version: 20250508174937,
        up: _migration_20250508174937_up,
        down: _migration_20250508174937_down,
      );
}
