// GENERATED CODE EDIT WITH CAUTION
// THIS FILE **WILL NOT** BE REGENERATED
// This file should be version controlled and can be manually edited.
part of 'schema.g.dart';

// While migrations are intelligently created, the difference between some commands, such as
// DropTable vs. RenameTable, cannot be determined. For this reason, please review migrations after
// they are created to ensure the correct inference was made.

// The migration version must **always** mirror the file name

const List<MigrationCommand> _migration_20250709072411_up = [
  DropColumn('members', onTable: 'Cooperative'),
  DropColumn('receiving_account_number', onTable: 'Transaction'),
  DropColumn('category', onTable: 'Wallet'),
  DropColumn('purpose', onTable: 'Wallet'),
  DropColumn('wallet_adress', onTable: 'Wallet'),
  DropColumn('account_id', onTable: 'Wallet'),
  DropColumn('phone_number', onTable: 'Wallet'),
  DropColumn('created_at', onTable: 'Wallet'),
  DropColumn('updated_at', onTable: 'Wallet'),
  DropColumn('recent_balance', onTable: 'Wallet'),
  InsertTable('Asset'),
  InsertTable('FinancialArticle'),
  InsertTable('FinancialReport'),
  InsertTable('Group'),
  InsertTable('GroupMembers'),
  InsertTable('Loan'),
  InsertTable('Milestone'),
  InsertTable('Saving'),
  InsertColumn('category', Column.varchar, onTable: 'Asset'),
  InsertColumn('purpose', Column.varchar, onTable: 'Asset'),
  InsertColumn('id', Column.varchar, onTable: 'Asset'),
  InsertColumn('title', Column.varchar, onTable: 'Asset'),
  InsertColumn('wallet_address', Column.varchar, onTable: 'Asset'),
  InsertColumn('coop_id', Column.varchar, onTable: 'Asset'),
  InsertColumn('country', Column.varchar, onTable: 'Asset'),
  InsertColumn('city', Column.varchar, onTable: 'Asset'),
  InsertColumn('province', Column.varchar, onTable: 'Asset'),
  InsertColumn('neighborhood', Column.varchar, onTable: 'Asset'),
  InsertColumn('status', Column.varchar, onTable: 'Asset'),
  InsertColumn('image_url', Column.varchar, onTable: 'Asset'),
  InsertColumn('created_at', Column.varchar, onTable: 'Asset'),
  InsertColumn('updated_at', Column.varchar, onTable: 'Asset'),
  InsertColumn('is_group_wallet', Column.boolean, onTable: 'Asset'),
  InsertColumn('asset_descriptive_name', Column.varchar, onTable: 'Asset'),
  InsertColumn('asset_description', Column.varchar, onTable: 'Asset'),
  InsertColumn('valuation_currency', Column.varchar, onTable: 'Asset'),
  InsertColumn('fiat_value', Column.Double, onTable: 'Asset'),
  InsertColumn('token_value', Column.Double, onTable: 'Asset'),
  InsertColumn('last_transaction_timestamp', Column.varchar, onTable: 'Asset'),
  InsertColumn('verifiable_certificate_issuer_id', Column.varchar, onTable: 'Asset'),
  InsertColumn('governing_board', Column.varchar, onTable: 'Asset'),
  InsertColumn('holding_account', Column.varchar, onTable: 'Asset'),
  InsertColumn('has_verifiable_certificate', Column.boolean, onTable: 'Asset'),
  InsertColumn('is_valuated', Column.boolean, onTable: 'Asset'),
  InsertColumn('is_minted', Column.boolean, onTable: 'Asset'),
  InsertColumn('is_shared', Column.boolean, onTable: 'Asset'),
  InsertColumn('is_active', Column.boolean, onTable: 'Asset'),
  InsertColumn('has_documents', Column.boolean, onTable: 'Asset'),
  InsertColumn('profile_id', Column.varchar, onTable: 'Asset'),
  InsertColumn('group_id', Column.varchar, onTable: 'Asset'),
  InsertColumn('has_received_vote', Column.boolean, onTable: 'Asset'),
  InsertColumn('amount_value', Column.Double, onTable: 'Asset'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'Cooperative'),
  InsertColumn('monthly_sub', Column.Double, onTable: 'Cooperative'),
  InsertColumn('id', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('created_at', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('profile_id', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('title', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('content_type', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('body', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('excerpt', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('cover_image', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('is_free', Column.boolean, onTable: 'FinancialArticle'),
  InsertColumn('price', Column.Double, onTable: 'FinancialArticle'),
  InsertColumn('currency', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('reading_time', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('published_at', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('status', Column.varchar, onTable: 'FinancialArticle'),
  InsertColumn('views', Column.integer, onTable: 'FinancialArticle'),
  InsertColumn('likes', Column.integer, onTable: 'FinancialArticle'),
  InsertColumn('comments_enabled', Column.boolean, onTable: 'FinancialArticle'),
  InsertColumn('transaction_id', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('amount', Column.Double, onTable: 'FinancialReport'),
  InsertColumn('currency', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('narrative', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('created_at', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('period_type', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('period_start', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('period_end', Column.varchar, onTable: 'FinancialReport'),
  InsertColumn('id', Column.varchar, onTable: 'Group', unique: true),
  InsertColumn('admin_id', Column.varchar, onTable: 'Group'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'Group'),
  InsertColumn('name', Column.varchar, onTable: 'Group'),
  InsertColumn('city', Column.varchar, onTable: 'Group'),
  InsertColumn('country', Column.varchar, onTable: 'Group'),
  InsertColumn('monthly_sub', Column.Double, onTable: 'Group'),
  InsertColumn('interest_rate', Column.Double, onTable: 'Group'),
  InsertColumn('id', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('member_id', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('created_at', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('role', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('cooperative_id', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('updated_at', Column.varchar, onTable: 'GroupMembers'),
  InsertColumn('id', Column.varchar, onTable: 'Loan', unique: true),
  InsertColumn('created_at', Column.varchar, onTable: 'Loan'),
  InsertColumn('borrower_wallet_id', Column.varchar, onTable: 'Loan'),
  InsertColumn('lender_wallet_id', Column.varchar, onTable: 'Loan'),
  InsertColumn('principal_amount', Column.num, onTable: 'Loan'),
  InsertColumn('interest_rate', Column.num, onTable: 'Loan'),
  InsertColumn('loan_term_months', Column.num, onTable: 'Loan'),
  InsertColumn('due_date', Column.varchar, onTable: 'Loan'),
  InsertColumn('status', Column.varchar, onTable: 'Loan'),
  InsertColumn('remaining_balance', Column.num, onTable: 'Loan'),
  InsertColumn('last_payment_date', Column.varchar, onTable: 'Loan'),
  InsertColumn('next_payment_date', Column.varchar, onTable: 'Loan'),
  InsertColumn('payment_amount', Column.num, onTable: 'Loan'),
  InsertColumn('loan_purpose', Column.varchar, onTable: 'Loan'),
  InsertColumn('collateral_description', Column.varchar, onTable: 'Loan'),
  InsertColumn('profile_id', Column.varchar, onTable: 'Loan'),
  InsertColumn('cooperative_id', Column.varchar, onTable: 'Loan'),
  InsertColumn('updated_at', Column.varchar, onTable: 'Loan'),
  InsertColumn('has_received_vote', Column.boolean, onTable: 'Loan'),
  InsertColumn('name', Column.varchar, onTable: 'Milestone'),
  InsertColumn('amount', Column.varchar, onTable: 'Milestone'),
  InsertColumn('status', Column.varchar, onTable: 'Profile'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'Profile'),
  InsertColumn('id', Column.varchar, onTable: 'Saving', unique: true),
  InsertColumn('created_at', Column.varchar, onTable: 'Saving'),
  InsertColumn('wallet_id', Column.varchar, onTable: 'Saving'),
  InsertColumn('profile_id', Column.varchar, onTable: 'Saving'),
  InsertColumn('group_id', Column.varchar, onTable: 'Saving'),
  InsertColumn('purpose', Column.varchar, onTable: 'Saving'),
  InsertColumn('lock_event', Column.varchar, onTable: 'Saving'),
  InsertColumn('current_balance', Column.num, onTable: 'Saving'),
  InsertColumn('lock_feature', Column.varchar, onTable: 'Saving'),
  InsertColumn('lock_date', Column.varchar, onTable: 'Saving'),
  InsertColumn('lock_amount', Column.num, onTable: 'Saving'),
  InsertColumn('endorser_id', Column.varchar, onTable: 'Saving'),
  InsertColumn('unlocking_code', Column.varchar, onTable: 'Saving'),
  InsertColumn('status', Column.varchar, onTable: 'Saving'),
  InsertColumn('is_locked', Column.boolean, onTable: 'Saving'),
  InsertColumn('unlock_key', Column.varchar, onTable: 'Saving'),
  InsertColumn('last_recommendation', Column.varchar, onTable: 'Saving'),
  InsertColumn('previous_deposit_date', Column.varchar, onTable: 'Saving'),
  InsertColumn('transaction_type', Column.varchar, onTable: 'Transaction'),
  InsertColumn('currency', Column.varchar, onTable: 'Transaction'),
  InsertColumn('narrative', Column.varchar, onTable: 'Transaction'),
  InsertColumn('holding_account', Column.varchar, onTable: 'Wallet'),
  InsertColumn('address', Column.varchar, onTable: 'Wallet'),
  InsertColumn('balance', Column.Double, onTable: 'Wallet'),
  InsertColumn('last_transaction_timestamp', Column.varchar, onTable: 'Wallet'),
  InsertColumn('parent_wallet_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('provider', Column.varchar, onTable: 'Wallet'),
  InsertColumn('default_currency', Column.varchar, onTable: 'Wallet'),
  InsertColumn('business_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('is_shared', Column.boolean, onTable: 'Wallet'),
  InsertColumn('is_active', Column.boolean, onTable: 'Wallet'),
  InsertColumn('is_sub_wallet', Column.boolean, onTable: 'Wallet'),
  InsertColumn('profile_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('coop_id', Column.varchar, onTable: 'Wallet'),
  InsertColumn('is_group_wallet', Column.boolean, onTable: 'Wallet'),
  InsertColumn('group_id', Column.varchar, onTable: 'Wallet')
];

const List<MigrationCommand> _migration_20250709072411_down = [
  DropTable('Asset'),
  DropTable('FinancialArticle'),
  DropTable('FinancialReport'),
  DropTable('Group'),
  DropTable('GroupMembers'),
  DropTable('Loan'),
  DropTable('Milestone'),
  DropTable('Saving'),
  DropColumn('category', onTable: 'Asset'),
  DropColumn('purpose', onTable: 'Asset'),
  DropColumn('id', onTable: 'Asset'),
  DropColumn('title', onTable: 'Asset'),
  DropColumn('wallet_address', onTable: 'Asset'),
  DropColumn('coop_id', onTable: 'Asset'),
  DropColumn('country', onTable: 'Asset'),
  DropColumn('city', onTable: 'Asset'),
  DropColumn('province', onTable: 'Asset'),
  DropColumn('neighborhood', onTable: 'Asset'),
  DropColumn('status', onTable: 'Asset'),
  DropColumn('image_url', onTable: 'Asset'),
  DropColumn('created_at', onTable: 'Asset'),
  DropColumn('updated_at', onTable: 'Asset'),
  DropColumn('is_group_wallet', onTable: 'Asset'),
  DropColumn('asset_descriptive_name', onTable: 'Asset'),
  DropColumn('asset_description', onTable: 'Asset'),
  DropColumn('valuation_currency', onTable: 'Asset'),
  DropColumn('fiat_value', onTable: 'Asset'),
  DropColumn('token_value', onTable: 'Asset'),
  DropColumn('last_transaction_timestamp', onTable: 'Asset'),
  DropColumn('verifiable_certificate_issuer_id', onTable: 'Asset'),
  DropColumn('governing_board', onTable: 'Asset'),
  DropColumn('holding_account', onTable: 'Asset'),
  DropColumn('has_verifiable_certificate', onTable: 'Asset'),
  DropColumn('is_valuated', onTable: 'Asset'),
  DropColumn('is_minted', onTable: 'Asset'),
  DropColumn('is_shared', onTable: 'Asset'),
  DropColumn('is_active', onTable: 'Asset'),
  DropColumn('has_documents', onTable: 'Asset'),
  DropColumn('profile_id', onTable: 'Asset'),
  DropColumn('group_id', onTable: 'Asset'),
  DropColumn('has_received_vote', onTable: 'Asset'),
  DropColumn('amount_value', onTable: 'Asset'),
  DropColumn('wallet_id', onTable: 'Cooperative'),
  DropColumn('monthly_sub', onTable: 'Cooperative'),
  DropColumn('id', onTable: 'FinancialArticle'),
  DropColumn('created_at', onTable: 'FinancialArticle'),
  DropColumn('profile_id', onTable: 'FinancialArticle'),
  DropColumn('title', onTable: 'FinancialArticle'),
  DropColumn('content_type', onTable: 'FinancialArticle'),
  DropColumn('body', onTable: 'FinancialArticle'),
  DropColumn('excerpt', onTable: 'FinancialArticle'),
  DropColumn('cover_image', onTable: 'FinancialArticle'),
  DropColumn('is_free', onTable: 'FinancialArticle'),
  DropColumn('price', onTable: 'FinancialArticle'),
  DropColumn('currency', onTable: 'FinancialArticle'),
  DropColumn('reading_time', onTable: 'FinancialArticle'),
  DropColumn('published_at', onTable: 'FinancialArticle'),
  DropColumn('status', onTable: 'FinancialArticle'),
  DropColumn('views', onTable: 'FinancialArticle'),
  DropColumn('likes', onTable: 'FinancialArticle'),
  DropColumn('comments_enabled', onTable: 'FinancialArticle'),
  DropColumn('transaction_id', onTable: 'FinancialReport'),
  DropColumn('amount', onTable: 'FinancialReport'),
  DropColumn('currency', onTable: 'FinancialReport'),
  DropColumn('narrative', onTable: 'FinancialReport'),
  DropColumn('created_at', onTable: 'FinancialReport'),
  DropColumn('period_type', onTable: 'FinancialReport'),
  DropColumn('period_start', onTable: 'FinancialReport'),
  DropColumn('period_end', onTable: 'FinancialReport'),
  DropColumn('id', onTable: 'Group'),
  DropColumn('admin_id', onTable: 'Group'),
  DropColumn('wallet_id', onTable: 'Group'),
  DropColumn('name', onTable: 'Group'),
  DropColumn('city', onTable: 'Group'),
  DropColumn('country', onTable: 'Group'),
  DropColumn('monthly_sub', onTable: 'Group'),
  DropColumn('interest_rate', onTable: 'Group'),
  DropColumn('id', onTable: 'GroupMembers'),
  DropColumn('member_id', onTable: 'GroupMembers'),
  DropColumn('created_at', onTable: 'GroupMembers'),
  DropColumn('role', onTable: 'GroupMembers'),
  DropColumn('cooperative_id', onTable: 'GroupMembers'),
  DropColumn('updated_at', onTable: 'GroupMembers'),
  DropColumn('id', onTable: 'Loan'),
  DropColumn('created_at', onTable: 'Loan'),
  DropColumn('borrower_wallet_id', onTable: 'Loan'),
  DropColumn('lender_wallet_id', onTable: 'Loan'),
  DropColumn('principal_amount', onTable: 'Loan'),
  DropColumn('interest_rate', onTable: 'Loan'),
  DropColumn('loan_term_months', onTable: 'Loan'),
  DropColumn('due_date', onTable: 'Loan'),
  DropColumn('status', onTable: 'Loan'),
  DropColumn('remaining_balance', onTable: 'Loan'),
  DropColumn('last_payment_date', onTable: 'Loan'),
  DropColumn('next_payment_date', onTable: 'Loan'),
  DropColumn('payment_amount', onTable: 'Loan'),
  DropColumn('loan_purpose', onTable: 'Loan'),
  DropColumn('collateral_description', onTable: 'Loan'),
  DropColumn('profile_id', onTable: 'Loan'),
  DropColumn('cooperative_id', onTable: 'Loan'),
  DropColumn('updated_at', onTable: 'Loan'),
  DropColumn('has_received_vote', onTable: 'Loan'),
  DropColumn('name', onTable: 'Milestone'),
  DropColumn('amount', onTable: 'Milestone'),
  DropColumn('status', onTable: 'Profile'),
  DropColumn('wallet_id', onTable: 'Profile'),
  DropColumn('id', onTable: 'Saving'),
  DropColumn('created_at', onTable: 'Saving'),
  DropColumn('wallet_id', onTable: 'Saving'),
  DropColumn('profile_id', onTable: 'Saving'),
  DropColumn('group_id', onTable: 'Saving'),
  DropColumn('purpose', onTable: 'Saving'),
  DropColumn('lock_event', onTable: 'Saving'),
  DropColumn('current_balance', onTable: 'Saving'),
  DropColumn('lock_feature', onTable: 'Saving'),
  DropColumn('lock_date', onTable: 'Saving'),
  DropColumn('lock_amount', onTable: 'Saving'),
  DropColumn('endorser_id', onTable: 'Saving'),
  DropColumn('unlocking_code', onTable: 'Saving'),
  DropColumn('status', onTable: 'Saving'),
  DropColumn('is_locked', onTable: 'Saving'),
  DropColumn('unlock_key', onTable: 'Saving'),
  DropColumn('last_recommendation', onTable: 'Saving'),
  DropColumn('previous_deposit_date', onTable: 'Saving'),
  DropColumn('transaction_type', onTable: 'Transaction'),
  DropColumn('currency', onTable: 'Transaction'),
  DropColumn('narrative', onTable: 'Transaction'),
  DropColumn('holding_account', onTable: 'Wallet'),
  DropColumn('address', onTable: 'Wallet'),
  DropColumn('balance', onTable: 'Wallet'),
  DropColumn('last_transaction_timestamp', onTable: 'Wallet'),
  DropColumn('parent_wallet_id', onTable: 'Wallet'),
  DropColumn('provider', onTable: 'Wallet'),
  DropColumn('default_currency', onTable: 'Wallet'),
  DropColumn('business_id', onTable: 'Wallet'),
  DropColumn('is_shared', onTable: 'Wallet'),
  DropColumn('is_active', onTable: 'Wallet'),
  DropColumn('is_sub_wallet', onTable: 'Wallet'),
  DropColumn('profile_id', onTable: 'Wallet'),
  DropColumn('coop_id', onTable: 'Wallet'),
  DropColumn('is_group_wallet', onTable: 'Wallet'),
  DropColumn('group_id', onTable: 'Wallet')
];

//
// DO NOT EDIT BELOW THIS LINE
//

@Migratable(
  version: '20250709072411',
  up: _migration_20250709072411_up,
  down: _migration_20250709072411_down,
)
class Migration20250709072411 extends Migration {
  const Migration20250709072411()
    : super(
        version: 20250709072411,
        up: _migration_20250709072411_up,
        down: _migration_20250709072411_down,
      );
}
