// GENERATED CODE DO NOT EDIT
// This file should be version controlled
import 'package:brick_sqlite/db.dart';
part '20250508174937.migration.dart';
part '20250508175234.migration.dart';
part '20250709072411.migration.dart';
part '20250709122004.migration.dart';
part '20250709123943.migration.dart';
part '20250710103418.migration.dart';
part '20250710104858.migration.dart';

/// All intelligently-generated migrations from all `@Migratable` classes on disk
final migrations = <Migration>{
  const Migration20250508174937(),
  const Migration20250508175234(),
  const Migration20250709072411(),
  const Migration20250709122004(),
  const Migration20250709123943(),
  const Migration20250710103418(),
  const Migration20250710104858(),
};

/// A consumable database structure including the latest generated migration.
final schema = Schema(
  20250710104858,
  generatorVersion: 1,
  tables: <SchemaTable>{
    SchemaTable(
      'Asset',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('holding_account', Column.varchar),
        SchemaColumn('valuation_currency', Column.varchar),
        SchemaColumn('fiat_value', Column.Double),
        SchemaColumn('token_value', Column.Double),
        SchemaColumn('governing_board', Column.varchar),
        SchemaColumn('last_transaction_timestamp', Column.varchar),
        SchemaColumn('verifiable_certificate_issuer_id', Column.varchar),
        SchemaColumn('has_verifiable_certificate', Column.boolean),
        SchemaColumn('is_valuated', Column.boolean),
        SchemaColumn('is_minted', Column.boolean),
        SchemaColumn('is_shared', Column.boolean),
        SchemaColumn('is_active', Column.boolean),
        SchemaColumn('has_documents', Column.boolean),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('updated_at', Column.varchar),
        SchemaColumn('profile_id', Column.varchar),
        SchemaColumn('group_id', Column.varchar),
        SchemaColumn('asset_description', Column.varchar),
        SchemaColumn('asset_descriptive_name', Column.varchar),
        SchemaColumn('category', Column.varchar),
        SchemaColumn('company_name', Column.varchar),
        SchemaColumn('email', Column.varchar),
        SchemaColumn('has_received_vote', Column.boolean),
        SchemaColumn('ownership_type', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      '_brick_Cooperative_members',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn(
          'l_Cooperative_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Cooperative',
          onDeleteCascade: true,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'f_Profile_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Profile',
          onDeleteCascade: true,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(
          columns: ['l_Cooperative_brick_id', 'f_Profile_brick_id'],
          unique: true,
        ),
      },
    ),
    SchemaTable(
      'Cooperative',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('wallet_id', Column.varchar),
        SchemaColumn('category', Column.varchar),
        SchemaColumn('city', Column.varchar),
        SchemaColumn('county', Column.varchar),
        SchemaColumn('province_state', Column.varchar),
        SchemaColumn('admin_id', Column.varchar),
        SchemaColumn('monthly_sub', Column.Double),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'FinancialArticle',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('profile_id', Column.varchar),
        SchemaColumn('title', Column.varchar),
        SchemaColumn('content_type', Column.varchar),
        SchemaColumn('body', Column.varchar),
        SchemaColumn('excerpt', Column.varchar),
        SchemaColumn('cover_image', Column.varchar),
        SchemaColumn('is_free', Column.boolean),
        SchemaColumn('price', Column.Double),
        SchemaColumn('currency', Column.varchar),
        SchemaColumn('reading_time', Column.varchar),
        SchemaColumn('published_at', Column.varchar),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('views', Column.integer),
        SchemaColumn('likes', Column.integer),
        SchemaColumn('comments_enabled', Column.boolean),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'FinancialReport',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('transaction_id', Column.varchar),
        SchemaColumn('amount', Column.Double),
        SchemaColumn('currency', Column.varchar),
        SchemaColumn('narrative', Column.varchar),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('period_type', Column.varchar),
        SchemaColumn('period_start', Column.varchar),
        SchemaColumn('period_end', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Group',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('admin_id', Column.varchar),
        SchemaColumn('wallet_id', Column.varchar),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('city', Column.varchar),
        SchemaColumn('country', Column.varchar),
        SchemaColumn('monthly_sub', Column.Double),
        SchemaColumn('interest_rate', Column.Double),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'GroupMembers',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('member_id', Column.varchar),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('role', Column.varchar),
        SchemaColumn('cooperative_id', Column.varchar),
        SchemaColumn('updated_at', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Loan',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('borrower_wallet_id', Column.varchar),
        SchemaColumn('lender_wallet_id', Column.varchar),
        SchemaColumn('principal_amount', Column.num),
        SchemaColumn('interest_rate', Column.num),
        SchemaColumn('loan_term_months', Column.num),
        SchemaColumn('due_date', Column.varchar),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('remaining_balance', Column.num),
        SchemaColumn('last_payment_date', Column.varchar),
        SchemaColumn('next_payment_date', Column.varchar),
        SchemaColumn('payment_amount', Column.num),
        SchemaColumn('loan_purpose', Column.varchar),
        SchemaColumn('collateral_description', Column.varchar),
        SchemaColumn('profile_id', Column.varchar),
        SchemaColumn('cooperative_id', Column.varchar),
        SchemaColumn('updated_at', Column.varchar),
        SchemaColumn('has_received_vote', Column.boolean),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Milestone',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('name', Column.varchar),
        SchemaColumn('amount', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Profile',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('password', Column.varchar),
        SchemaColumn('profile_image_url', Column.varchar),
        SchemaColumn('profile_image_id', Column.varchar),
        SchemaColumn('gender', Column.varchar),
        SchemaColumn('first_name', Column.varchar),
        SchemaColumn('last_name', Column.varchar),
        SchemaColumn('full_name', Column.varchar),
        SchemaColumn('profile_picture_id', Column.varchar),
        SchemaColumn('account_type', Column.varchar),
        SchemaColumn('email', Column.varchar),
        SchemaColumn('phone', Column.varchar),
        SchemaColumn('city', Column.varchar),
        SchemaColumn('country', Column.varchar),
        SchemaColumn('neighbourhood', Column.varchar),
        SchemaColumn('province_state', Column.varchar),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('wallet_balance', Column.Double),
        SchemaColumn('wallet_address', Column.varchar),
        SchemaColumn('wallet_id', Column.varchar),
        SchemaColumn('push_token', Column.varchar),
        SchemaColumn('business', Column.varchar),
        SchemaColumn('last_access', Column.datetime),
        SchemaColumn('created_at', Column.datetime),
        SchemaColumn('updated_at', Column.datetime),
        SchemaColumn('permissions', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      '_brick_Saving_lock_milestones',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn(
          'l_Saving_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Saving',
          onDeleteCascade: true,
          onDeleteSetDefault: false,
        ),
        SchemaColumn(
          'f_Milestone_brick_id',
          Column.integer,
          isForeignKey: true,
          foreignTableName: 'Milestone',
          onDeleteCascade: true,
          onDeleteSetDefault: false,
        ),
      },
      indices: <SchemaIndex>{
        SchemaIndex(
          columns: ['l_Saving_brick_id', 'f_Milestone_brick_id'],
          unique: true,
        ),
      },
    ),
    SchemaTable(
      'Saving',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar, unique: true),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('wallet_id', Column.varchar),
        SchemaColumn('profile_id', Column.varchar),
        SchemaColumn('group_id', Column.varchar),
        SchemaColumn('purpose', Column.varchar),
        SchemaColumn('lock_event', Column.varchar),
        SchemaColumn('current_balance', Column.num),
        SchemaColumn('lock_feature', Column.varchar),
        SchemaColumn('lock_date', Column.varchar),
        SchemaColumn('lock_amount', Column.num),
        SchemaColumn('endorser_id', Column.varchar),
        SchemaColumn('unlocking_code', Column.varchar),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('is_locked', Column.boolean),
        SchemaColumn('unlock_key', Column.varchar),
        SchemaColumn('last_recommendation', Column.varchar),
        SchemaColumn('previous_deposit_date', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Transaction',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('category', Column.varchar),
        SchemaColumn('purpose', Column.varchar),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('sending_wallet', Column.varchar),
        SchemaColumn('account_id', Column.varchar),
        SchemaColumn('sending_phone', Column.varchar),
        SchemaColumn('receiving_wallet', Column.varchar),
        SchemaColumn('receiving_phone', Column.varchar),
        SchemaColumn('recieving_profile_avatar', Column.varchar),
        SchemaColumn('sending_profile_avatar', Column.varchar),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('transfer_mode', Column.varchar),
        SchemaColumn('transaction_type', Column.varchar),
        SchemaColumn('transfer_category', Column.varchar),
        SchemaColumn('amount', Column.Double),
        SchemaColumn('created_at', Column.varchar),
        SchemaColumn('updated_at', Column.varchar),
        SchemaColumn('currency', Column.varchar),
        SchemaColumn('narrative', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
    SchemaTable(
      'Wallet',
      columns: <SchemaColumn>{
        SchemaColumn(
          '_brick_id',
          Column.integer,
          autoincrement: true,
          nullable: false,
          isPrimaryKey: true,
        ),
        SchemaColumn('id', Column.varchar),
        SchemaColumn('holding_account', Column.varchar),
        SchemaColumn('address', Column.varchar),
        SchemaColumn('status', Column.varchar),
        SchemaColumn('balance', Column.Double),
        SchemaColumn('last_transaction_timestamp', Column.varchar),
        SchemaColumn('parent_wallet_id', Column.varchar),
        SchemaColumn('provider', Column.varchar),
        SchemaColumn('default_currency', Column.varchar),
        SchemaColumn('business_id', Column.varchar),
        SchemaColumn('is_shared', Column.boolean),
        SchemaColumn('is_active', Column.boolean),
        SchemaColumn('is_sub_wallet', Column.boolean),
        SchemaColumn('profile_id', Column.varchar),
        SchemaColumn('coop_id', Column.varchar),
        SchemaColumn('is_group_wallet', Column.boolean),
        SchemaColumn('group_id', Column.varchar),
      },
      indices: <SchemaIndex>{},
    ),
  },
);
