// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ_5gGwoQk5nHyMERKbP4GpfHugLk6zFU',
    appId: '1:972015824763:web:19152a0c73ee20a8d457de',
    messagingSenderId: '972015824763',
    projectId: 'mukai-sacco-management-systems',
    authDomain: 'mukai-sacco-management-systems.firebaseapp.com',
    storageBucket: 'mukai-sacco-management-systems.firebasestorage.app',
    measurementId: 'G-TD3BYL5N46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiSKbhgfO7AusMMQAg7Ygf5znzDhmE-X4',
    appId: '1:972015824763:android:be1a4315961a9f70d457de',
    messagingSenderId: '972015824763',
    projectId: 'mukai-sacco-management-systems',
    storageBucket: 'mukai-sacco-management-systems.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJt40Yaveb1DrXKSQW_PbDjDsRateihU',
    appId: '1:972015824763:ios:4efbceb36c2ec4fbd457de',
    messagingSenderId: '972015824763',
    projectId: 'mukai-sacco-management-systems',
    storageBucket: 'mukai-sacco-management-systems.firebasestorage.app',
    iosBundleId: 'com.example.doladayApp',
  );

}