part of 'app_pages.dart';

abstract class Routes {
  static const splash = _Paths.splash;
  static const login = _Paths.login;
  static const register = _Paths.register;
  static const home = _Paths.home;
  static const onboarding = _Paths.otp;
  static const otp = _Paths.otp;
  static const bottomBar = _Paths.bottomBar;
  static const transactionDetail = _Paths.transactionDetail;
  static const editTransaction = _Paths.editTransaction;
  static const addAccount = _Paths.addAccount;
  static const recentTransaction = _Paths.recentTransaction;
  static const profile = _Paths.profile;
  static const editProfile = _Paths.editProfile;
  static const privacyPolicy = _Paths.privacyPolicy;
  static const termsAndCondition = _Paths.termsAndCondition;
  static const transaction = _Paths.transaction;
  static const addTransaction = _Paths.addTransaction;
  static const addIncomeExpense = _Paths.addIncomeExpense;
  static const budget = _Paths.budget;
  static const setBudget = _Paths.setBudget;
  static const editBudget = _Paths.editBudget;
  static const account = _Paths.account;
  static const editAccount = _Paths.editAccount;
  static const accountTransactions = _Paths.accountTransactions;
  static const saleOrderDetail = _Paths.saleOrderDetail;
  static const addBusiness = _Paths.addBusiness;
  static const addProduct = _Paths.addProduct;
  static const productDetail = _Paths.productDetail;
  static const businessDetail = _Paths.businessDetail;
  static const businessList = _Paths.businessList;
  static const ecommerceProductDetail = _Paths.ecommerceProductDetail;
  static const checkoutScreen = _Paths.checkoutScreen;
  static const addressesListScreen = _Paths.addressesListScreen;
  static const addAddressScreen = _Paths.addAddressScreen;
  static const cartScreen = _Paths.cartScreen;
  static const addMarketScreen = _Paths.addMarketScreen;
  static const marketsListScreen = _Paths.marketsListScreen;
  static const marketDetailScreen = _Paths.marketDetailScreen;
  static const notificationListScreen = _Paths.notificationListScreen;
  static const accountOrdersList = _Paths.accountOrdersList;
  static const accountBusinessList = _Paths.accountBusinessList;
  static const requestTransport = _Paths.requestTransport;
}

abstract class _Paths {
  static const splash = '/splash';
  static const login = '/login';
  static const register = '/register';
  static const home = '/home';
  // static const onboarding = '/onboarding';
  static const requestTransport = '/requestTransport';
  static const otp = '/otp';
  static const bottomBar = '/bottomBar';
  static const transactionDetail = '/transactionDetail';
  static const editTransaction = '/editTransaction';
  static const addAccount = '/addAccount';
  static const recentTransaction = '/recentTransaction';
  static const profile = '/profile';
  static const editProfile = '/editProfile';
  static const privacyPolicy = '/privacyPolicy';
  static const termsAndCondition = '/termsAndCondition';
  static const transaction = '/transaction';
  static const addTransaction = '/addTransaction';
  static const addIncomeExpense = '/addIncomeExpense';
  static const budget = '/budget';
  static const setBudget = '/setBudget';
  static const editBudget = '/editBudget';
  static const account = '/account';
  static const editAccount = '/editAccount';
  static const accountTransactions = '/accountTransactions';
  static const saleOrderDetail = '/saleOrderDetail';
  static const addBusiness = '/addBusiness';
  static const addProduct = '/addProduct';
  static const productDetail = '/productDetail';
  static const businessDetail = '/businessDetail';
  static const ecommerceProductDetail = '/ecommerceProductDetail';
  static const businessList = '/businessList';
  static const checkoutScreen = '/checkoutScreen';
  static const cartScreen = '/cartScreen';
  static const addAddressScreen = '/addAddressScreen';
  static const addressesListScreen = '/addressesListScreen';
  static const marketDetailScreen = '/marketDetailScreen';
  static const addMarketScreen = '/addMarketScreen';
  static const marketsListScreen = '/marketsListScreen';
  static const notificationListScreen = '/notificationListScreen';

  // orders
  static const accountOrdersList = '/accountOrdersList';
  static const accountBusinessList = '/accountBusinessList';
}
